export const LIMITS = {
  MAX_DESCRIPTION_BYTES: 5 * 1024, // 5 KB
  MAX_METADATA_BYTES: 20 * 1024, // 20 KB
  MAX_SCREENSHOT_BYTES: 5 * 1024 * 1024, // 5 MB
  MAX_BREADCRUMBS: 40,
  MAX_CONSOLE_EVENTS: 100,
  MAX_NETWORK_EVENTS: 100,
  MAX_SCREENSHOT_DIMENSION: 3000,
};

export const RATE_LIMITS = {
  IP_MAX_REQUESTS: 20,
  IP_WINDOW_SECONDS: 10 * 60, // 10 minutes
  PROJECT_MAX_REQUESTS: 100,
  PROJECT_WINDOW_SECONDS: 60 * 60, // 1 hour
};

export const REPORT_STATUS = {
  OPEN: "OPEN",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED: "RESOLVED",
  IGNORED: "IGNORED",
  DUPLICATE: "DUPLICATE",
};

export const REPORT_SEVERITY = {
  P0: "P0",
  P1: "P1",
  P2: "P2",
  P3: "P3",
};

export const API_KEY_STATUS = {
  ACTIVE: "ACTIVE",
  REVOKED: "REVOKED",
};

export const INTEGRATION_TYPES = {
  GITHUB: "GITHUB",
  TELEGRAM: "TELEGRAM",
  EMAIL: "EMAIL",
};
